import { selectItemType } from "@/config/types/types";

export const districtOptions: selectItemType[] = [
    { _id: "zila0", label: "Select District", value: "" },
    { _id: "zila1", label: "Bagerhat", value: "bagerhat" },
    { _id: "zila2", label: "Bandarban", value: "bandarban" },
    { _id: "zila3", label: "Barguna", value: "barguna" },
    { _id: "zila4", label: "Barishal", value: "barishal" },
    { _id: "zila5", label: "Bhola", value: "bhola" },
    { _id: "zila6", label: "Bogra", value: "bogra" },
    { _id: "zila7", label: "Brahmanbaria", value: "brahmanbaria" },
    { _id: "zila8", label: "Chandpur", value: "chandpur" },
    { _id: "zila9", label: "Chapai Nawabganj", value: "chapai-nawabganj" },
    { _id: "zila10", label: "Chattogram", value: "chattogram" },
    { _id: "zila11", label: "Chuadanga", value: "chuadanga" },
    { _id: "zila12", label: "Cox's Bazar", value: "coxs-bazar" },
    { _id: "zila13", label: "Cumilla", value: "cumilla" },
    { _id: "zila14", label: "Dhaka", value: "dhaka" },
    { _id: "zila15", label: "Dinajpur", value: "dinajpur" },
    { _id: "zila16", label: "Faridpur", value: "faridpur" },
    { _id: "zila17", label: "Feni", value: "feni" },
    { _id: "zila18", label: "Gaibandha", value: "gaibandha" },
    { _id: "zila19", label: "Gazipur", value: "gazipur" },
    { _id: "zila20", label: "Gopalganj", value: "gopalganj" },
    { _id: "zila21", label: "Habiganj", value: "habiganj" },
    { _id: "zila22", label: "Jamalpur", value: "jamalpur" },
    { _id: "zila23", label: "Jashore", value: "jashore" },
    { _id: "zila24", label: "Jhalakati", value: "jhalakati" },
    { _id: "zila25", label: "Jhenaidah", value: "jhenaidah" },
    { _id: "zila26", label: "Joypurhat", value: "joypurhat" },
    { _id: "zila27", label: "Khagrachhari", value: "khagrachhari" },
    { _id: "zila28", label: "Khulna", value: "khulna" },
    { _id: "zila29", label: "Kishoreganj", value: "kishoreganj" },
    { _id: "zila30", label: "Kurigram", value: "kurigram" },
    { _id: "zila31", label: "Kushtia", value: "kushtia" },
    { _id: "zila32", label: "Lakshmipur", value: "lakshmipur" },
    { _id: "zila33", label: "Lalmonirhat", value: "lalmonirhat" },
    { _id: "zila34", label: "Manikganj", value: "manikganj" },
    { _id: "zila35", label: "Madaripur", value: "madaripur" },
    { _id: "zila36", label: "Magura", value: "magura" },
    { _id: "zila37", label: "Meherpur", value: "meherpur" },
    { _id: "zila38", label: "Moulvibazar", value: "moulvibazar" },
    { _id: "zila39", label: "Munshiganj", value: "munshiganj" },
    { _id: "zila40", label: "Mymensingh", value: "mymensingh" },
    { _id: "zila41", label: "Naogaon", value: "naogaon" },
    { _id: "zila42", label: "Narail", value: "narail" },
    { _id: "zila43", label: "Narayanganj", value: "narayanganj" },
    { _id: "zila44", label: "Narsingdi", value: "narsingdi" },
    { _id: "zila45", label: "Natore", value: "natore" },
    { _id: "zila46", label: "Nawabganj", value: "nawabganj" },
    { _id: "zila47", label: "Netrokona", value: "netrokona" },
    { _id: "zila48", label: "Nilphamari", value: "nilphamari" },
    { _id: "zila49", label: "Noakhali", value: "noakhali" },
    { _id: "zila50", label: "Pabna", value: "pabna" },
    { _id: "zila51", label: "Panchagarh", value: "panchagarh" },
    { _id: "zila52", label: "Patuakhali", value: "patuakhali" },
    { _id: "zila53", label: "Pirojpur", value: "pirojpur" },
    { _id: "zila54", label: "Rajbari", value: "rajbari" },
    { _id: "zila55", label: "Rajshahi", value: "rajshahi" },
    { _id: "zila56", label: "Rangamati", value: "rangamati" },
    { _id: "zila57", label: "Rangpur", value: "rangpur" },
    { _id: "zila58", label: "Satkhira", value: "satkhira" },
    { _id: "zila59", label: "Shariatpur", value: "shariatpur" },
    { _id: "zila60", label: "Sherpur", value: "sherpur" },
    { _id: "zila61", label: "Sirajganj", value: "sirajganj" },
    { _id: "zila62", label: "Sunamganj", value: "sunamganj" },
    { _id: "zila63", label: "Sylhet", value: "sylhet" },
    { _id: "zila64", label: "Tangail", value: "tangail" },
    { _id: "zila65", label: "Thakurgaon", value: "thakurgaon" },
]